import { isAppError, CustomAppException, Resultat } from "@ww/reference";
import { logConsole } from "@ww/reference";

export function handleApiCriticalError(error: any, context: string = ""): never {
  const emoji = "üå∑‚Äã‚Äã‚Äã‚Äã";
  const viewLog = true;

  logConsole(viewLog, emoji + " ‚ùå", context, 'error', error);

  // 1Ô∏è‚É£ Si backend renvoie un AppError
  if (error.response?.data && isAppError(error.response.data)) {
    const retour: Resultat = {
      success: false,
      message: error.response.data.message || "",
      erreur: error.response.data
    };
    throw new CustomAppException(retour);
  }

  // 2Ô∏è‚É£ Si backend renvoie juste un message g√©n√©rique
  if (error.response?.data && typeof error.response.data === "object" && "message" in error.response.data) {
    const retour: Resultat = {
      success: false,
      message: error.response.data.message,
      erreur: error.response.data
    };
    throw new CustomAppException(retour);
  }

  // 3Ô∏è‚É£ Sinon on prend le message de l‚Äôexception Axios
  const message = error instanceof Error ? error.message : String(error);
  const retour: Resultat = {
    success: false,
    message: context ? `[${context}] ${message}` : message
  };
  throw new CustomAppException(retour);
}

export function handleApiError(error: any, context: string = ""):   Resultat {
  const emoji = "üå∑‚Äã‚Äã‚Äã‚Äã";
  const viewLog = true;

  logConsole(viewLog, emoji + " ‚ùå", context, 'error', error);

  // 1Ô∏è‚É£ Si backend renvoie un AppError
  if (error.response?.data && isAppError(error.response.data)) {
    const retour: Resultat = {
      success: false,
      message: error.response.data.message || "",
      erreur: error.response.data
    };
    //throw new CustomAppException(retour);
    return retour;
  }

  // 2Ô∏è‚É£ Si backend renvoie juste un message g√©n√©rique
  if (error.response?.data && typeof error.response.data === "object" && "message" in error.response.data) {
    const retour: Resultat = {
      success: false,
      message: error.response.data.message,
      erreur: error.response.data
    };
    //throw new CustomAppException(retour);
    return retour;
  }

  // 3Ô∏è‚É£ Sinon on prend le message de l‚Äôexception Axios
  const message = error instanceof Error ? error.message : String(error);
  const retour: Resultat = {
    success: false,
    message: context ? `[${context}] ${message}` : message
  };
  //throw new CustomAppException(retour);
  return retour;
}
